// <auto-generated />
using System;
using Hiring_and_Selection_Process_Platform.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hiring_and_Selection_Process_Platform.Migrations
{
    [DbContext(typeof(MyAppContext))]
    [Migration("20250524065342_Second")]
    partial class Second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hiring_and_Selection_Process_Platform.Models.Candidates", b =>
                {
                    b.Property<int>("candidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("candidateId"));

                    b.Property<int>("candidateAge")
                        .HasColumnType("int");

                    b.Property<string>("candidateContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("candidateEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("candidateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("candidateId");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("Hiring_and_Selection_Process_Platform.Models.Education", b =>
                {
                    b.Property<int>("educationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("educationId"));

                    b.Property<int>("candidateId")
                        .HasColumnType("int");

                    b.Property<int?>("candidatescandidateId")
                        .HasColumnType("int");

                    b.Property<double?>("cgpa")
                        .HasColumnType("float");

                    b.Property<string>("degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("educationTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("major")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("passingYear")
                        .HasColumnType("datetime2");

                    b.Property<string>("universityName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("educationId");

                    b.HasIndex("candidatescandidateId");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("Hiring_and_Selection_Process_Platform.Models.Job", b =>
                {
                    b.Property<int>("jobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("jobId"));

                    b.Property<DateTime?>("deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("jobCompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("jobDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("jobLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("jobRequirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("jobSalary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("jobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("jobType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("noEmployees")
                        .HasColumnType("int");

                    b.HasKey("jobId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Hiring_and_Selection_Process_Platform.Models.Education", b =>
                {
                    b.HasOne("Hiring_and_Selection_Process_Platform.Models.Candidates", "candidates")
                        .WithMany()
                        .HasForeignKey("candidatescandidateId");

                    b.Navigation("candidates");
                });
#pragma warning restore 612, 618
        }
    }
}
